apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
  name: {{ include "drone.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.DRONE_SERVER_PROTO | default "http" }}
      protocol: TCP
      name: {{ .Values.config.DRONE_SERVER_PROTO | default "http" }}
  selector:
    {{- include "drone.selectorLabels" . | nindent 4 }}
